/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as InitialisationRouteImport } from './routes/initialisation'
import { Route as AuthenticatedCatalogueRouteImport } from './routes/_authenticated/catalogue'
import { Route as AuthenticatedCommanderRouteImport } from './routes/_authenticated/commander'
import { Route as AuthenticatedComptesRouteImport } from './routes/_authenticated/comptes'
import { Route as AuthenticatedFichesRouteImport } from './routes/_authenticated/fiches'
import { Route as AuthenticatedTableauDeBordRouteImport } from './routes/_authenticated/tableau-de-bord'
import { Route as VerifierTokenRouteImport } from './routes/verifier.$token'
import { Route as AuthenticatedCampagnesIndexRouteImport } from './routes/_authenticated/campagnes.index'
import { Route as AuthenticatedCampagnesCampaignIdRouteImport } from './routes/_authenticated/campagnes.$campaignId'
import { Route as AuthenticatedCommandesIndexRouteImport } from './routes/_authenticated/commandes.index'
import { Route as AuthenticatedCommandesOrderIdRouteImport } from './routes/_authenticated/commandes.$orderId'
import { Route as AuthenticatedMesCommandesIndexRouteImport } from './routes/_authenticated/mes-commandes.index'
import { Route as AuthenticatedMesCommandesOrderIdRouteImport } from './routes/_authenticated/mes-commandes.$orderId'
import { Route as AuthenticatedSaisieIndexRouteImport } from './routes/_authenticated/saisie.index'
import { Route as AuthenticatedSaisieCampaignIdRouteImport } from './routes/_authenticated/saisie.$campaignId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const InitialisationRoute = InitialisationRouteImport.update({
  id: '/initialisation',
  path: '/initialisation',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCatalogueRoute = AuthenticatedCatalogueRouteImport.update({
  id: '/catalogue',
  path: '/catalogue',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCommanderRoute = AuthenticatedCommanderRouteImport.update({
  id: '/commander',
  path: '/commander',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedComptesRoute = AuthenticatedComptesRouteImport.update({
  id: '/comptes',
  path: '/comptes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFichesRoute = AuthenticatedFichesRouteImport.update({
  id: '/fiches',
  path: '/fiches',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTableauDeBordRoute =
  AuthenticatedTableauDeBordRouteImport.update({
    id: '/tableau-de-bord',
    path: '/tableau-de-bord',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const VerifierTokenRoute = VerifierTokenRouteImport.update({
  id: '/verifier/$token',
  path: '/verifier/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCampagnesIndexRoute =
  AuthenticatedCampagnesIndexRouteImport.update({
    id: '/campagnes/',
    path: '/campagnes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCampagnesCampaignIdRoute =
  AuthenticatedCampagnesCampaignIdRouteImport.update({
    id: '/campagnes/$campaignId',
    path: '/campagnes/$campaignId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCommandesIndexRoute =
  AuthenticatedCommandesIndexRouteImport.update({
    id: '/commandes/',
    path: '/commandes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCommandesOrderIdRoute =
  AuthenticatedCommandesOrderIdRouteImport.update({
    id: '/commandes/$orderId',
    path: '/commandes/$orderId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMesCommandesIndexRoute =
  AuthenticatedMesCommandesIndexRouteImport.update({
    id: '/mes-commandes/',
    path: '/mes-commandes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMesCommandesOrderIdRoute =
  AuthenticatedMesCommandesOrderIdRouteImport.update({
    id: '/mes-commandes/$orderId',
    path: '/mes-commandes/$orderId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSaisieIndexRoute =
  AuthenticatedSaisieIndexRouteImport.update({
    id: '/saisie/',
    path: '/saisie/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSaisieCampaignIdRoute =
  AuthenticatedSaisieCampaignIdRouteImport.update({
    id: '/saisie/$campaignId',
    path: '/saisie/$campaignId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/initialisation': typeof InitialisationRoute
  '/catalogue': typeof AuthenticatedCatalogueRoute
  '/commander': typeof AuthenticatedCommanderRoute
  '/comptes': typeof AuthenticatedComptesRoute
  '/fiches': typeof AuthenticatedFichesRoute
  '/tableau-de-bord': typeof AuthenticatedTableauDeBordRoute
  '/verifier/$token': typeof VerifierTokenRoute
  '/campagnes/$campaignId': typeof AuthenticatedCampagnesCampaignIdRoute
  '/commandes/$orderId': typeof AuthenticatedCommandesOrderIdRoute
  '/mes-commandes/$orderId': typeof AuthenticatedMesCommandesOrderIdRoute
  '/saisie/$campaignId': typeof AuthenticatedSaisieCampaignIdRoute
  '/campagnes/': typeof AuthenticatedCampagnesIndexRoute
  '/commandes/': typeof AuthenticatedCommandesIndexRoute
  '/mes-commandes/': typeof AuthenticatedMesCommandesIndexRoute
  '/saisie/': typeof AuthenticatedSaisieIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/initialisation': typeof InitialisationRoute
  '/catalogue': typeof AuthenticatedCatalogueRoute
  '/commander': typeof AuthenticatedCommanderRoute
  '/comptes': typeof AuthenticatedComptesRoute
  '/fiches': typeof AuthenticatedFichesRoute
  '/tableau-de-bord': typeof AuthenticatedTableauDeBordRoute
  '/verifier/$token': typeof VerifierTokenRoute
  '/campagnes/$campaignId': typeof AuthenticatedCampagnesCampaignIdRoute
  '/commandes/$orderId': typeof AuthenticatedCommandesOrderIdRoute
  '/mes-commandes/$orderId': typeof AuthenticatedMesCommandesOrderIdRoute
  '/saisie/$campaignId': typeof AuthenticatedSaisieCampaignIdRoute
  '/campagnes': typeof AuthenticatedCampagnesIndexRoute
  '/commandes': typeof AuthenticatedCommandesIndexRoute
  '/mes-commandes': typeof AuthenticatedMesCommandesIndexRoute
  '/saisie': typeof AuthenticatedSaisieIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/initialisation': typeof InitialisationRoute
  '/_authenticated/catalogue': typeof AuthenticatedCatalogueRoute
  '/_authenticated/commander': typeof AuthenticatedCommanderRoute
  '/_authenticated/comptes': typeof AuthenticatedComptesRoute
  '/_authenticated/fiches': typeof AuthenticatedFichesRoute
  '/_authenticated/tableau-de-bord': typeof AuthenticatedTableauDeBordRoute
  '/verifier/$token': typeof VerifierTokenRoute
  '/_authenticated/campagnes/$campaignId': typeof AuthenticatedCampagnesCampaignIdRoute
  '/_authenticated/commandes/$orderId': typeof AuthenticatedCommandesOrderIdRoute
  '/_authenticated/mes-commandes/$orderId': typeof AuthenticatedMesCommandesOrderIdRoute
  '/_authenticated/saisie/$campaignId': typeof AuthenticatedSaisieCampaignIdRoute
  '/_authenticated/campagnes/': typeof AuthenticatedCampagnesIndexRoute
  '/_authenticated/commandes/': typeof AuthenticatedCommandesIndexRoute
  '/_authenticated/mes-commandes/': typeof AuthenticatedMesCommandesIndexRoute
  '/_authenticated/saisie/': typeof AuthenticatedSaisieIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/initialisation'
    | '/catalogue'
    | '/commander'
    | '/comptes'
    | '/fiches'
    | '/tableau-de-bord'
    | '/verifier/$token'
    | '/campagnes/$campaignId'
    | '/commandes/$orderId'
    | '/mes-commandes/$orderId'
    | '/saisie/$campaignId'
    | '/campagnes/'
    | '/commandes/'
    | '/mes-commandes/'
    | '/saisie/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/initialisation'
    | '/catalogue'
    | '/commander'
    | '/comptes'
    | '/fiches'
    | '/tableau-de-bord'
    | '/verifier/$token'
    | '/campagnes/$campaignId'
    | '/commandes/$orderId'
    | '/mes-commandes/$orderId'
    | '/saisie/$campaignId'
    | '/campagnes'
    | '/commandes'
    | '/mes-commandes'
    | '/saisie'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/initialisation'
    | '/_authenticated/catalogue'
    | '/_authenticated/commander'
    | '/_authenticated/comptes'
    | '/_authenticated/fiches'
    | '/_authenticated/tableau-de-bord'
    | '/verifier/$token'
    | '/_authenticated/campagnes/$campaignId'
    | '/_authenticated/commandes/$orderId'
    | '/_authenticated/mes-commandes/$orderId'
    | '/_authenticated/saisie/$campaignId'
    | '/_authenticated/campagnes/'
    | '/_authenticated/commandes/'
    | '/_authenticated/mes-commandes/'
    | '/_authenticated/saisie/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  InitialisationRoute: typeof InitialisationRoute
  VerifierTokenRoute: typeof VerifierTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/initialisation': {
      id: '/initialisation'
      path: '/initialisation'
      fullPath: '/initialisation'
      preLoaderRoute: typeof InitialisationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/catalogue': {
      id: '/_authenticated/catalogue'
      path: '/catalogue'
      fullPath: '/catalogue'
      preLoaderRoute: typeof AuthenticatedCatalogueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/commander': {
      id: '/_authenticated/commander'
      path: '/commander'
      fullPath: '/commander'
      preLoaderRoute: typeof AuthenticatedCommanderRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/comptes': {
      id: '/_authenticated/comptes'
      path: '/comptes'
      fullPath: '/comptes'
      preLoaderRoute: typeof AuthenticatedComptesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fiches': {
      id: '/_authenticated/fiches'
      path: '/fiches'
      fullPath: '/fiches'
      preLoaderRoute: typeof AuthenticatedFichesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tableau-de-bord': {
      id: '/_authenticated/tableau-de-bord'
      path: '/tableau-de-bord'
      fullPath: '/tableau-de-bord'
      preLoaderRoute: typeof AuthenticatedTableauDeBordRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/verifier/$token': {
      id: '/verifier/$token'
      path: '/verifier/$token'
      fullPath: '/verifier/$token'
      preLoaderRoute: typeof VerifierTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/campagnes/': {
      id: '/_authenticated/campagnes/'
      path: '/campagnes'
      fullPath: '/campagnes/'
      preLoaderRoute: typeof AuthenticatedCampagnesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/campagnes/$campaignId': {
      id: '/_authenticated/campagnes/$campaignId'
      path: '/campagnes/$campaignId'
      fullPath: '/campagnes/$campaignId'
      preLoaderRoute: typeof AuthenticatedCampagnesCampaignIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/commandes/': {
      id: '/_authenticated/commandes/'
      path: '/commandes'
      fullPath: '/commandes/'
      preLoaderRoute: typeof AuthenticatedCommandesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/commandes/$orderId': {
      id: '/_authenticated/commandes/$orderId'
      path: '/commandes/$orderId'
      fullPath: '/commandes/$orderId'
      preLoaderRoute: typeof AuthenticatedCommandesOrderIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mes-commandes/': {
      id: '/_authenticated/mes-commandes/'
      path: '/mes-commandes'
      fullPath: '/mes-commandes/'
      preLoaderRoute: typeof AuthenticatedMesCommandesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mes-commandes/$orderId': {
      id: '/_authenticated/mes-commandes/$orderId'
      path: '/mes-commandes/$orderId'
      fullPath: '/mes-commandes/$orderId'
      preLoaderRoute: typeof AuthenticatedMesCommandesOrderIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/saisie/': {
      id: '/_authenticated/saisie/'
      path: '/saisie'
      fullPath: '/saisie/'
      preLoaderRoute: typeof AuthenticatedSaisieIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/saisie/$campaignId': {
      id: '/_authenticated/saisie/$campaignId'
      path: '/saisie/$campaignId'
      fullPath: '/saisie/$campaignId'
      preLoaderRoute: typeof AuthenticatedSaisieCampaignIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCatalogueRoute: typeof AuthenticatedCatalogueRoute
  AuthenticatedCommanderRoute: typeof AuthenticatedCommanderRoute
  AuthenticatedComptesRoute: typeof AuthenticatedComptesRoute
  AuthenticatedFichesRoute: typeof AuthenticatedFichesRoute
  AuthenticatedTableauDeBordRoute: typeof AuthenticatedTableauDeBordRoute
  AuthenticatedCampagnesCampaignIdRoute: typeof AuthenticatedCampagnesCampaignIdRoute
  AuthenticatedCommandesOrderIdRoute: typeof AuthenticatedCommandesOrderIdRoute
  AuthenticatedMesCommandesOrderIdRoute: typeof AuthenticatedMesCommandesOrderIdRoute
  AuthenticatedSaisieCampaignIdRoute: typeof AuthenticatedSaisieCampaignIdRoute
  AuthenticatedCampagnesIndexRoute: typeof AuthenticatedCampagnesIndexRoute
  AuthenticatedCommandesIndexRoute: typeof AuthenticatedCommandesIndexRoute
  AuthenticatedMesCommandesIndexRoute: typeof AuthenticatedMesCommandesIndexRoute
  AuthenticatedSaisieIndexRoute: typeof AuthenticatedSaisieIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCatalogueRoute: AuthenticatedCatalogueRoute,
  AuthenticatedCommanderRoute: AuthenticatedCommanderRoute,
  AuthenticatedComptesRoute: AuthenticatedComptesRoute,
  AuthenticatedFichesRoute: AuthenticatedFichesRoute,
  AuthenticatedTableauDeBordRoute: AuthenticatedTableauDeBordRoute,
  AuthenticatedCampagnesCampaignIdRoute: AuthenticatedCampagnesCampaignIdRoute,
  AuthenticatedCommandesOrderIdRoute: AuthenticatedCommandesOrderIdRoute,
  AuthenticatedMesCommandesOrderIdRoute: AuthenticatedMesCommandesOrderIdRoute,
  AuthenticatedSaisieCampaignIdRoute: AuthenticatedSaisieCampaignIdRoute,
  AuthenticatedCampagnesIndexRoute: AuthenticatedCampagnesIndexRoute,
  AuthenticatedCommandesIndexRoute: AuthenticatedCommandesIndexRoute,
  AuthenticatedMesCommandesIndexRoute: AuthenticatedMesCommandesIndexRoute,
  AuthenticatedSaisieIndexRoute: AuthenticatedSaisieIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  InitialisationRoute: InitialisationRoute,
  VerifierTokenRoute: VerifierTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
